spring:
  application:
    name: zomato-clone-backend

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    defer-datasource-initialization: true
    
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      mode: never
      data-locations: ${DATA_PATH}

  #Redis-locking configuration
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  cache:
    type: redis

server:
  servlet:
    context-path: /api/v1

  port: 8080
  address: 0.0.0.0

#Jwt - secret key
jwt:
  secretKey: ${JWT_SECRET_KEY}
  expiration: ${JWT_EXPIRATION_TIME}

stripe:
  secret-key: ${STRIPE_SECRET_KEY}
  webhook:
    secret: ${WEBHOOK_SECRET}

#logging properties
logging:
  pattern:
    level: %5p [reqId=%X{requestId}]